### PR TITLE
IDVA6-1182 - Add person success Page

### PR DESCRIPTION
**Pull request by bwallace-ch**
Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-1182

Changes:
- Created add person success page with interface functionality
- Added unit tests with extraData functionality

### CODE REVIEW

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Review by mmodzelewski-ch — APPROVED** [review]

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Pull request merged**
