### PR TITLE
IDVA6 1252 Update authorised agent dashboard

### PR DESCRIPTION
**Pull request by bmchugh-ch**
Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-1252

Changes:

- updated authorised agent dashboard with latest design changes and links

### CODE REVIEW

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Review by mmodzelewski-ch — APPROVED** [review]

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Pull request closed without merging**
