### PR TITLE
IDVA6 1310 Are you sure you want to remove yourself?

### PR DESCRIPTION
**Pull request by bmchugh-ch**
Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-1310

Changes:

- Adds basic add and remove user functionality for testing purposes. 
- Add removing yourself page design and additional checks when a person removes themselves

### CODE REVIEW

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Review by mmodzelewski-ch — APPROVED** [review]

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Pull request merged**
