### PR TITLE
IDVA6-1490 Modify navbar to conditionally show "Authorised agent"

### PR DESCRIPTION
**Pull request by mmodzelewski-ch**
Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-1490

Changes:
- Authorised agent link in navbar shown based on ACSP number existing in the session thanks to updated version of ch-node-utils

### CODE REVIEW

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Review by kkonuganti-ch — APPROVED** [review]

**Review by bmchugh-ch — APPROVED** [review]

**Pull request merged**
